"""Utility functions for data manipulation, validation, and tabularization."""

from .discovery import all_displays, all_estimators, all_functions
from .panel import (
    dict_to_panel,
    get_group_df,
    inspect_locality,
    inspect_panel,
    panel_aware_prefix,
    panel_aware_rename,
    panel_aware_suffix,
    select_panel_columns,
)
from .pivot import window_futures
from .polars import cast, get_numeric_columns
from .tabularization import tabularize
from .tags import (
    CLASS_PROBA,
    INTERVAL,
    POINT,
    POINT_INTERVAL,
    ForecasterTags,
    InputTags,
    SplitterTags,
    Tags,
    TargetTags,
    TransformerTags,
)
from .validate_data import (
    validate_forecaster_data,
    validate_plotting_data,
    validate_plotting_params,
    validate_scorer_data,
    validate_splitter_data,
    validate_transformer_data,
)
from .validation import (
    add_interval,
    check_continuity,
    check_forecasting_horizon_positive,
    check_groups,
    check_groups_exist,
    check_inputs,
    check_interval_consistency,
    check_panel_groups_match,
    check_panel_internal_consistency,
    check_schema,
    check_scorer_column_selection,
    check_sufficient_rows,
    check_time_column,
    check_X_actual_required,
    interval_to_timedelta,
    parse_interval,
    validate_column_names,
    validate_search_data,
)
from .weighting import (
    BaseWeighter,
    CompositeWeighter,
    ExponentialDecayWeighter,
    LinearDecayWeighter,
    LookupWeighter,
    SeasonalEmphasisWeighter,
    TableWeighter,
    combine_weight_vectors,
    normalize_weights,
    resolve_weighter_to_array,
    validate_weight_array,
)

__all__ = [
    "CLASS_PROBA",
    "BaseWeighter",
    "ExponentialDecayWeighter",
    "ForecasterTags",
    "INTERVAL",
    "InputTags",
    "LinearDecayWeighter",
    "LookupWeighter",
    "POINT",
    "POINT_INTERVAL",
    "CompositeWeighter",
    "SeasonalEmphasisWeighter",
    "SplitterTags",
    "TableWeighter",
    "Tags",
    "TargetTags",
    "TransformerTags",
    "add_interval",
    "all_displays",
    "all_estimators",
    "all_functions",
    "cast",
    "check_continuity",
    "check_X_actual_required",
    "check_forecasting_horizon_positive",
    "check_inputs",
    "check_interval_consistency",
    "check_groups",
    "check_groups_exist",
    "check_panel_groups_match",
    "check_panel_internal_consistency",
    "check_schema",
    "check_scorer_column_selection",
    "check_sufficient_rows",
    "check_time_column",
    "combine_weight_vectors",
    "dict_to_panel",
    "get_group_df",
    "get_numeric_columns",
    "inspect_locality",
    "inspect_panel",
    "interval_to_timedelta",
    "normalize_weights",
    "panel_aware_prefix",
    "panel_aware_rename",
    "panel_aware_suffix",
    "parse_interval",
    "resolve_weighter_to_array",
    "select_panel_columns",
    "tabularize",
    "validate_column_names",
    "validate_forecaster_data",
    "validate_plotting_data",
    "validate_plotting_params",
    "validate_scorer_data",
    "validate_search_data",
    "validate_splitter_data",
    "validate_transformer_data",
    "validate_weight_array",
    "window_futures",
]
