name: Build and release package

on:
  push:
    tags:
      - 'v*.*.*'

env:
  dists-artifact-name: python-package-distributions

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
          cache-dependency-glob: "pyproject.toml"
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build package
        run: uv build --python 3.12 --python-preference only-managed --sdist --wheel . --out-dir dist

      - name: Check distributions
        run: uvx twine check dist/*

      - name: Store the distribution packages
        uses: actions/upload-artifact@v5
        with:
          name: ${{ env.dists-artifact-name }}
          path: dist/*

  pypi-publish:
    name: upload release to PyPI
    needs:
      - build
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/yohou
    permissions:
      id-token: write
    steps:
      - name: Download all the dists
        uses: actions/download-artifact@v6
        with:
          name: ${{ env.dists-artifact-name }}
          path: dist/

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          attestations: true
          verify-metadata: false
